Acme\StoreBundle\Entity\ProductNew:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        price:
            type: float
            length: null
        description:
            type: text
            length: null
    lifecycleCallbacks: {  }
